[Interface]
PrivateKey = YIGGLuoA4dKnUuuV5fZ9lRjVNVj3huTlz7zHLJ8MN2k=
Address = 10.0.0.16
DNS = 1.1.1.1

[Peer]
PublicKey = k40eae5omYmj3y0V4fEfytFDUtbCbvhN1GQHV2J50mo=
Endpoint = 20.211.153.141:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
